### ISSUE TITLE
Write additional stt tests

### ISSUE THREAD

**Issue by ianhajra** [ianhajra/virtual_assistant#30]
Add a bunch more tests to test_stt.py to verify that the speech to text functionality will work properly within the virtual assistant.

These tests should cover use cases, such as the following statements:

"Volume Up"
"Volume Down"
etc.

Place these into a new function, labeled something like
def test_stt_use_cases()

**Comment by chungjryan** [comment]
using this website: https://ttsmaker.com/
to make the audio samples
